### ISSUE TITLE
Release Wicket 8.x compatible version

### ISSUE THREAD

**Issue by martin-g** [jennybrown8/wicket-source#2]
Hi Jenny,

Could you please make a release against Wicket 8.x (e.g. 8.0.0-M4) ?
Here I use locally built 8.0.0-SNAPSHOT but others prefer to use a proper release (https://github.com/MarcGiffing/wicket-spring-boot/issues/78).
If you don't want to deal with Sonatype accounts then an option would be to move this project to WicketStuff.

Thanks!

**Comment by jennybrown8** [comment]
I'll see what I can get figured out for this.  Thanks for the note.

**Comment by jennybrown8** [comment]
https://repo1.maven.org/maven2/com/github/jennybrown8/wicket-source/

It lives!  I don't see it in the central repo's public search yet, but it's on the site and I assume it will be added to the search index shortly.  If you notice any problems with the release please let me know.  Thanks!

**Comment by martin-g** [comment]
Thank you!
