### ISSUE TITLE
Release Wicket 9.x compatible version

### ISSUE THREAD

**Issue by martin-g** [jennybrown8/wicket-source#4]
Hi Jenny,

Could you please make a release against Wicket 9.x ?
Wicket 9.0.0 is being voted right now but you could use 9.0.0-M5 too since it is API compatible.

Thank you!

**Comment by martin-g** [comment]
https://github.com/MarcGiffing/wicket-spring-boot/issues/184

**Comment by jennybrown8** [comment]
I released 9.0.0 to maven central.  Might take a day for the caches to update.

**Comment by martin-g** [comment]
Thank you!
